server:
  port: 8080

spring:
  application:
    name: ruida-dev-env
  datasource:
    url: jdbc:mysql://47.101.129.111:3306/runoob?characterEncoding=utf8&useSSl=false&serverTimezone=GMT%2B8
    username: root
    password: Chenjy418.
    driver-class-name: com.mysql.cj.jdbc.Driver


config:
  image:
    path: E:/upload/image/