server:
  port: 8090

spring:
  application:
    name: ruida-test-env
  datasource:
    url: jdbc:mysql://47.101.129.111:3306/runoob?characterEncoding=utf8&useSSl=false&serverTimeZone=Asia/Shanghai
    username: root
    password: Chenjy418.
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: none

config:
  image:
    path: E:/upload/image/